# Generated by Django 2.0.6 on 2018-06-19 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
