# Generated by Django 2.1.4 on 2018-12-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeApi', '0003_balancehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancehistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='balancehistory',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
