# Generated by Django 2.1.4 on 2018-12-17 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeApi', '0004_auto_20181217_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
