# Generated by Django 2.1.4 on 2018-12-21 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeApi', '0005_auto_20181217_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_idd', models.IntegerField(default=-1, unique=True)),
                ('payment_id', models.IntegerField(default=-1)),
                ('payment_name', models.CharField(default='', max_length=256)),
                ('transaction_description', models.CharField(default='', max_length=1024)),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=-1, max_digits=12)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=-1, max_digits=12)),
                ('transaction_exists', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
