# Generated by Django 2.1.4 on 2018-12-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeApi', '0006_transactionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='transactionId',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='payment_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='transaction_id',
            field=models.IntegerField(default=-1, unique=True),
        ),
    ]
